apiVersion: v1
kind: Pod
metadata:
  name: aws-cli2
  namespace: dev
spec:
  serviceAccountName: s3-sa
  containers:
  - name: aws-cli
    image: public.ecr.aws/aws-cli/aws-cli
    command:
      - sleep
      - "3600"