apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: ingress
  annotations:
    #nginx.ingress.kubernetes.io/upstream-hash-by: "true"
    nginx.ingress.kubernetes.io/group.name: "ssgpang"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    #nginx.ingress.kubernetes.io/upstream-hash-by: "true"
    nginx.ingress.kubernetes.io/group.name: "ssgpang"
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.monitor.jumjoo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  annotations:
    #nginx.ingress.kubernetes.io/upstream-hash-by: "true"
    nginx.ingress.kubernetes.io/group.name: "ssgpang"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.monitor.jumjoo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80