apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::206177862976:role/ssg-final-3-oidc-s3-role
    # IAM Role에 있는 arn 값을 지정