apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: was-dep
  labels:
    app: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      serviceAccountName: storage-sa
      containers:
      - name: was
        image: jjy4041/ssgpang:2f84c654cf8eab97585c2d96518b386678b55b75
        ports:
        - containerPort: 80
        env:
        - name: AZURE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: AZURE_CONNECTION_STRING
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: GITHUB_TOKEN
        - name: CLOUD_PROVIDER
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: CLOUD_PROVIDER
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"